version: "3.9"

services:

  eureka-server:
    build:
      context: .
      dockerfile: ./eureka-server/Dockerfile
      args:
        MODULE_NAME: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ms-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ms-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - ms-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ms-network


  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
      args:
        MODULE_NAME: auth-service
    container_name: auth-service
    depends_on:
      - eureka-server
      - postgres
    environment:
      JWT_SECRET: THIS_IS_A_VERY_LONG_SECRET_KEY_FOR_JWT_123456
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8091:8091"
    networks:
      - ms-network


  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
      args:
        MODULE_NAME: product-service
    container_name: product-service
    depends_on:
      - eureka-server
      - postgres
      - kafka
    environment:
      JWT_SECRET: THIS_IS_A_VERY_LONG_SECRET_KEY_FOR_JWT_123456
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8083:8083"
    networks:
      - ms-network

  price-service:
    build:
      context: .
      dockerfile: ./price-service/Dockerfile
      args:
        MODULE_NAME: price-service
    container_name: price-service
    depends_on:
      - eureka-server
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - ms-network

  product-detail-service:
    build:
      context: .
      dockerfile: ./product-detail-service/Dockerfile
      args:
        MODULE_NAME: product-detail-service
    container_name: product-detail-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ecommerce
    ports:
      - "8082:8082"
    networks:
      - ms-network

  cart-service:
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
      args:
        MODULE_NAME: cart-service
    container_name: cart-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ecommerce
    ports:
      - "8084:8084"
    networks:
      - ms-network

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
      args:
        MODULE_NAME: order-service
    container_name: order-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ecommerce
    ports:
      - "8085:8085"
    networks:
      - ms-network

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
      args:
        MODULE_NAME: notification-service
    container_name: notification-service
    depends_on:
      - eureka-server
      - mongo
      - kafka
    environment:
          SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ecommerce
    ports:
      - "8086:8086"
    networks:
      - ms-network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
      args:
        MODULE_NAME: api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8090:8090"
    networks:
      - ms-network

  zipkin:
      image: openzipkin/zipkin
      container_name: zipkin
      ports:
        - "9411:9411"
      networks:
        - ms-network

networks:
  ms-network:
    driver: bridge

volumes:
  pg_data:
  mongo_data:
